version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=letmein
